/* soapprojectstatsProxy.cpp
   Generated by gSOAP 2.8.4 from servicedescription.h

Copyright(C) 2000-2011, Robert van Engelen, Genivia Inc. All Rights Reserved.
The generated code is released under one of the following licenses:
1) GPL or 2) Genivia's license for commercial use.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
*/

#include "soapprojectstatsProxy.h"

projectstatsProxy::projectstatsProxy()
{	this->soap = soap_new();
	this->own = true;
	projectstatsProxy_init(SOAP_IO_DEFAULT, SOAP_IO_DEFAULT);
}

projectstatsProxy::projectstatsProxy(struct soap *_soap)
{	this->soap = _soap;
	this->own = false;
	projectstatsProxy_init(_soap->imode, _soap->omode);
}

projectstatsProxy::projectstatsProxy(const char *url)
{	this->soap = soap_new();
	this->own = true;
	projectstatsProxy_init(SOAP_IO_DEFAULT, SOAP_IO_DEFAULT);
	soap_endpoint = url;
}

projectstatsProxy::projectstatsProxy(soap_mode iomode)
{	this->soap = soap_new();
	this->own = true;
	projectstatsProxy_init(iomode, iomode);
}

projectstatsProxy::projectstatsProxy(const char *url, soap_mode iomode)
{	this->soap = soap_new();
	this->own = true;
	projectstatsProxy_init(iomode, iomode);
	soap_endpoint = url;
}

projectstatsProxy::projectstatsProxy(soap_mode imode, soap_mode omode)
{	this->soap = soap_new();
	this->own = true;
	projectstatsProxy_init(imode, omode);
}

projectstatsProxy::~projectstatsProxy()
{	if (this->own)
		soap_free(this->soap);
}

void projectstatsProxy::projectstatsProxy_init(soap_mode imode, soap_mode omode)
{	soap_imode(this->soap, imode);
	soap_omode(this->soap, omode);
	soap_endpoint = NULL;
	static const struct Namespace namespaces[] =
{
	{"SOAP-ENV", "http://schemas.xmlsoap.org/soap/envelope/", "http://www.w3.org/*/soap-envelope", NULL},
	{"SOAP-ENC", "http://schemas.xmlsoap.org/soap/encoding/", "http://www.w3.org/*/soap-encoding", NULL},
	{"xsi", "http://www.w3.org/2001/XMLSchema-instance", "http://www.w3.org/*/XMLSchema-instance", NULL},
	{"xsd", "http://www.w3.org/2001/XMLSchema", "http://www.w3.org/*/XMLSchema", NULL},
	{"ps", "urn:projectstats", NULL, NULL},
	{NULL, NULL, NULL, NULL}
};
	soap_set_namespaces(this->soap, namespaces);
}

void projectstatsProxy::destroy()
{	soap_destroy(this->soap);
	soap_end(this->soap);
}

void projectstatsProxy::soap_noheader()
{	this->soap->header = NULL;
}

const SOAP_ENV__Header *projectstatsProxy::soap_header()
{	return this->soap->header;
}

const SOAP_ENV__Fault *projectstatsProxy::soap_fault()
{	return this->soap->fault;
}

const char *projectstatsProxy::soap_fault_string()
{	return *soap_faultstring(this->soap);
}

const char *projectstatsProxy::soap_fault_detail()
{	return *soap_faultdetail(this->soap);
}

int projectstatsProxy::soap_close_socket()
{	return soap_closesock(this->soap);
}

int projectstatsProxy::soap_force_close_socket()
{	return soap_force_closesock(this->soap);
}

void projectstatsProxy::soap_print_fault(FILE *fd)
{	::soap_print_fault(this->soap, fd);
}

#ifndef WITH_LEAN
void projectstatsProxy::soap_stream_fault(std::ostream& os)
{	::soap_stream_fault(this->soap, os);
}

char *projectstatsProxy::soap_sprint_fault(char *buf, size_t len)
{	return ::soap_sprint_fault(this->soap, buf, len);
}
#endif

int projectstatsProxy::playerById(const char *endpoint, const char *soap_action, int id, PlayerInformation &result)
{	struct soap *soap = this->soap;
	struct ps__playerById soap_tmp_ps__playerById;
	struct ps__playerByIdResponse *soap_tmp_ps__playerByIdResponse;
	if (endpoint)
		soap_endpoint = endpoint;
	if (!soap_endpoint)
		soap_endpoint = "http://eineurl.von.uns?";
	if (!soap_action)
		soap_action = "";
	soap->encodingStyle = NULL;
	soap_tmp_ps__playerById.id = id;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize_ps__playerById(soap, &soap_tmp_ps__playerById);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ps__playerById(soap, &soap_tmp_ps__playerById, "ps:playerById", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ps__playerById(soap, &soap_tmp_ps__playerById, "ps:playerById", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!&result)
		return soap_closesock(soap);
	result.soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_tmp_ps__playerByIdResponse = soap_get_ps__playerByIdResponse(soap, NULL, "ps:playerByIdResponse", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	result = soap_tmp_ps__playerByIdResponse->result;
	return soap_closesock(soap);
}
/* End of client proxy code */
