/* soapprojectstatsService.h
   Generated by gSOAP 2.8.4 from servicedescription.h

Copyright(C) 2000-2011, Robert van Engelen, Genivia Inc. All Rights Reserved.
The generated code is released under one of the following licenses:
1) GPL or 2) Genivia's license for commercial use.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
*/

#ifndef soapprojectstatsService_H
#define soapprojectstatsService_H
#include "soapH.h"
class SOAP_CMAC projectstatsService : public soap
{ public:
	/// Constructor
	projectstatsService();
	/// Constructor with copy of another engine state
	projectstatsService(const struct soap&);
	/// Constructor with engine input+output mode control
	projectstatsService(soap_mode iomode);
	/// Constructor with engine input and output mode control
	projectstatsService(soap_mode imode, soap_mode omode);
	/// Destructor, also frees all deserialized data
	virtual ~projectstatsService();
	/// Delete all deserialized data (uses soap_destroy and soap_end)
	virtual	void destroy();
	/// Initializer used by constructor
	virtual	void projectstatsService_init(soap_mode imode, soap_mode omode);
	/// Create a copy
	virtual	projectstatsService *copy() SOAP_PURE_VIRTUAL;
	/// Close connection (normally automatic)
	virtual	int soap_close_socket();
	/// Force close connection (can kill a thread blocked on IO)
	virtual	int soap_force_close_socket();
	/// Return sender-related fault to sender
	virtual	int soap_senderfault(const char *string, const char *detailXML);
	/// Return sender-related fault with SOAP 1.2 subcode to sender
	virtual	int soap_senderfault(const char *subcodeQName, const char *string, const char *detailXML);
	/// Return receiver-related fault to sender
	virtual	int soap_receiverfault(const char *string, const char *detailXML);
	/// Return receiver-related fault with SOAP 1.2 subcode to sender
	virtual	int soap_receiverfault(const char *subcodeQName, const char *string, const char *detailXML);
	/// Print fault
	virtual	void soap_print_fault(FILE*);
#ifndef WITH_LEAN
	/// Print fault to stream
	virtual	void soap_stream_fault(std::ostream&);
	/// Put fault into buffer
	virtual	char *soap_sprint_fault(char *buf, size_t len);
#endif
	/// Disables and removes SOAP Header from message
	virtual	void soap_noheader();
	/// Get SOAP Header structure (NULL when absent)
	virtual	const SOAP_ENV__Header *soap_header();
	/// Run simple single-thread iterative service on port until a connection error occurs (returns error code or SOAP_OK), use this->bind_flag = SO_REUSEADDR to rebind for a rerun
	virtual	int run(int port);
	/// Bind service to port (returns master socket or SOAP_INVALID_SOCKET)
	virtual	SOAP_SOCKET bind(const char *host, int port, int backlog);
	/// Accept next request (returns socket or SOAP_INVALID_SOCKET)
	virtual	SOAP_SOCKET accept();
	/// Serve this request (returns error code or SOAP_OK)
	virtual	int serve();
	/// Used by serve() to dispatch a request (returns error code or SOAP_OK)
	virtual	int dispatch();

	///
	/// Service operations (you should define these):
	/// Note: compile with -DWITH_PURE_VIRTUAL for pure virtual methods
	///

	/// Web service operation 'playerById' (returns error code or SOAP_OK)
	virtual	int playerById(int id, PlayerInformation &result) SOAP_PURE_VIRTUAL;

	/// Web service operation 'playerList' (returns error code or SOAP_OK)
	virtual	int playerList(PlayerList &result) SOAP_PURE_VIRTUAL;

	/// Web service operation 'drinkList' (returns error code or SOAP_OK)
	virtual	int drinkList(DrinkList &result) SOAP_PURE_VIRTUAL;

	/// Web service operation 'placeList' (returns error code or SOAP_OK)
	virtual	int placeList(PlaceList &result) SOAP_PURE_VIRTUAL;

	/// Web service operation 'gameList' (returns error code or SOAP_OK)
	virtual	int gameList(GameList &result) SOAP_PURE_VIRTUAL;

	/// Web service operation 'gameCurrentPlayingPlayers' (returns error code or SOAP_OK)
	virtual	int gameCurrentPlayingPlayers(int gameId, PlayerList &result) SOAP_PURE_VIRTUAL;

	/// Web service operation 'addSchmeisserei' (returns error code or SOAP_OK)
	virtual	int addSchmeisserei(int gameId, int playerId, std::string type, std::string &result) SOAP_PURE_VIRTUAL;

	/// Web service operation 'addDrink' (returns error code or SOAP_OK)
	virtual	int addDrink(int gameId, int playerId, int drinkId, std::string &result) SOAP_PURE_VIRTUAL;

	/// Web service operation 'addRound' (returns error code or SOAP_OK)
	virtual	int addRound(int gameId, int re1PlayerId, int re2PlayerId, int hochzeitPlayerId, int schweinereiPlayerId, int trumpfabgabePlayerId, std::string soloType, bool pflichtsolo, int points, std::string comment, std::string &result) SOAP_PURE_VIRTUAL;

	/// Web service operation 'hasPflichtSolo' (returns error code or SOAP_OK)
	virtual	int hasPflichtSolo(int playerId, int gameId, bool &result) SOAP_PURE_VIRTUAL;
};
#endif
